import DataTable from 'datatables.net-dt';

export default (Alpine) => {
    Alpine.data('datatables', ({
        ajax = null,
        ajaxData = {},
        autoWidth = undefined,
        caption = undefined,
        columns = [],
        data = [],
        deferLoading = null,
        deferRender = null,
        destroy = null,
        displayStart = null,
        info = true,
        lengthChange = false,
        lengthMenu = [10, 25, 50, 100],
        livewireId,
        order = [],
        ordering = true,
        orderMulti = false,
        pageLength = null,
        paging = true,
        pagingType = null,
        processing = true,
        renderer = null,
        retrieve = null,
        rowId = undefined,
        scrollCollapse = false,
        scrollX = false,
        scrollY = null,
        search = null,
        searchCols = null,
        searchDelay,
        searching,
        serverSide,
        getRecordsUsing = null,
    }) => ({
        init() {
            let ajaxCallback = ajax;

            if (getRecordsUsing !== null) {
                ajaxCallback = async function (data, callback) {
                    callback({
                        data: await Livewire.find(livewireId).call(getRecordsUsing),
                    });
                };
            }

            this.table = new DataTable(this.$refs.table, {
                    ajax: {
                        url: ajaxCallback,
                        data: ajaxData,
                        dataSrc: 'data',
                        method: 'POST',
                        headers: {
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
                        },
                    },
                    autoWidth,
                    caption,
                    columns,
                    // columnDefs: undefined,
                    data,
                    deferLoading,
                    deferRender,
                    destroy,
                    displayStart,
                    info,
                    // language: undefined,
                    // layout: undefined,
                    lengthChange,
                    lengthMenu,
                    // orderCellsTop: undefined,
                    // orderClasses: undefined,
                    // orderDescReverse: undefined,
                    order,
                    // orderFixed: undefined,
                    ordering,
                    orderMulti,
                    pageLength,
                    paging,
                    pagingType,
                    processing,
                    renderer,
                    retrieve,
                    rowId: rowId || undefined,
                    scrollCollapse,
                    scrollX,
                    scrollY,
                    search,
                    searchCols: searchCols || undefined,
                    searchDelay,
                    searching,
                    serverSide,
                    // stateDuration: undefined,
                    // stateSave: undefined,
                    // stripeClasses: undefined,
                    // tabIndex: undefined,
                    // createdRow: undefined,
                    // drawCallback: undefined,
                    // footerCallback: undefined,
                    // formatNumber: undefined,
                    // headerCallback: undefined,
                    // infoCallback: undefined,
                    // initComplete: undefined,
                    // preDrawCallback: undefined,
                    // rowCallback: undefined,
                    // stateLoadCallback: undefined,
                    // stateLoaded: undefined,
                    // stateLoadParams: undefined,
                    // stateSaveCallback: undefined,
                    // stateSaveParams: undefined,
                }
            );
        },
    }));
};
